"use client";

// Grocery list for a meal plan — ingredients summed across the day into
// buyable quantities, grouped by aisle. Generated by AI from the plan, then
// fully editable (tweak amounts, add/remove lines) and persisted by the parent.

import { useState, useEffect, useCallback } from "react";
import { X, Check, Plus, Trash2, Loader2, RefreshCw, ShoppingCart } from "lucide-react";

export type GroceryItem = { item: string; qty: string; note?: string };
export type GroceryCategory = { name: string; items: GroceryItem[] };
export type GroceryList = { categories: GroceryCategory[] };

type PlanBody = { meals?: { name?: string; items?: { food?: string; qty?: string }[] }[] };

export function GroceryListModal({
  plan, savedList, saving, onPersist, onClose,
}: {
  plan: PlanBody;
  savedList: GroceryList | null;
  saving?: boolean;
  onPersist: (list: GroceryList) => void;
  onClose: () => void;
}) {
  const [list, setList] = useState<GroceryList>(savedList ?? { categories: [] });
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generate = useCallback(async () => {
    setGenerating(true); setError(null);
    try {
      const r = await fetch("/api/ai/grocery-list", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ plan }),
      });
      const j = await r.json();
      if (!r.ok) throw new Error(j.error ?? "Couldn't build the list.");
      setList({ categories: Array.isArray(j.categories) ? j.categories : [] });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't build the list.");
    } finally { setGenerating(false); }
  }, [plan]);

  // First open with no saved list → generate.
  useEffect(() => { if (!savedList || savedList.categories.length === 0) void generate(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);

  function patch(ci: number, ii: number, p: Partial<GroceryItem>) {
    setList((l) => ({ categories: l.categories.map((c, i) => i !== ci ? c : { ...c, items: c.items.map((it, j) => j !== ii ? it : { ...it, ...p }) }) }));
  }
  function remove(ci: number, ii: number) {
    setList((l) => ({ categories: l.categories.map((c, i) => i !== ci ? c : { ...c, items: c.items.filter((_, j) => j !== ii) }).filter((c) => c.items.length > 0) }));
  }
  function addLine(ci: number) {
    setList((l) => ({ categories: l.categories.map((c, i) => i !== ci ? c : { ...c, items: [...c.items, { item: "", qty: "" }] }) }));
  }

  const empty = list.categories.every((c) => c.items.length === 0);

  return (
    <div className="fixed inset-0 z-[70] flex items-end sm:items-center justify-center p-0 sm:p-4">
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full sm:max-w-md bg-[#0D0D0D] border border-white/10 rounded-t-2xl sm:rounded-2xl shadow-2xl flex flex-col overflow-hidden max-h-[92dvh]">
        <div className="px-5 pt-5 pb-3 border-b border-white/[0.06] shrink-0 flex items-center justify-between">
          <div>
            <h2 className="text-sm font-semibold text-white/80 flex items-center gap-2"><ShoppingCart className="w-4 h-4 text-[#B48B40]" strokeWidth={1.8} /> Grocery list</h2>
            <p className="text-[11px] text-white/30 mt-0.5">Everything to buy for this plan — tweak the amounts.</p>
          </div>
          <button onClick={onClose} className="w-7 h-7 rounded-lg border border-white/8 bg-white/[0.03] flex items-center justify-center text-white/30 hover:text-white/65"><X className="w-3.5 h-3.5" strokeWidth={1.5} /></button>
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4" style={{ scrollbarWidth: "none" }}>
          {generating && empty ? (
            <div className="flex flex-col items-center justify-center py-10 gap-2 text-white/40">
              <Loader2 className="w-5 h-5 animate-spin text-[#B48B40]/60" /> <span className="text-xs">Building your list…</span>
            </div>
          ) : error && empty ? (
            <p className="text-[12px] text-[#EF4444]/70 text-center py-6">{error}</p>
          ) : (
            list.categories.map((cat, ci) => (
              <div key={ci}>
                <p className="text-[10px] uppercase tracking-[0.18em] text-[#B48B40]/70 mb-2">{cat.name}</p>
                <div className="space-y-1.5">
                  {cat.items.map((it, ii) => (
                    <div key={ii} className="flex items-center gap-2">
                      <input
                        value={it.qty}
                        onChange={(e) => patch(ci, ii, { qty: e.target.value })}
                        placeholder="qty"
                        className="w-20 bg-white/[0.04] border border-white/10 rounded-md px-2 py-1.5 text-[12px] text-white/80 outline-none focus:border-[#B48B40]/40 tabular-nums"
                      />
                      <input
                        value={it.item}
                        onChange={(e) => patch(ci, ii, { item: e.target.value })}
                        placeholder="item"
                        className="flex-1 min-w-0 bg-white/[0.04] border border-white/10 rounded-md px-2 py-1.5 text-[12px] text-white/80 outline-none focus:border-[#B48B40]/40"
                      />
                      <button onClick={() => remove(ci, ii)} className="shrink-0 w-6 h-6 rounded-md flex items-center justify-center text-white/20 hover:text-[#EF4444]/70 hover:bg-[#EF4444]/8"><Trash2 className="w-3 h-3" strokeWidth={1.6} /></button>
                    </div>
                  ))}
                  <button onClick={() => addLine(ci)} className="text-[11px] text-white/30 hover:text-white/55 inline-flex items-center gap-1"><Plus className="w-3 h-3" strokeWidth={1.6} /> Add</button>
                </div>
              </div>
            ))
          )}
        </div>

        <div className="px-5 pt-3 border-t border-white/[0.05] shrink-0 flex gap-2.5" style={{ paddingBottom: "calc(env(safe-area-inset-bottom) + 1rem)" }}>
          <button onClick={generate} disabled={generating} className="inline-flex items-center gap-1.5 px-3 py-2.5 rounded-xl border border-white/10 text-xs font-medium text-white/45 hover:text-white/70 disabled:opacity-50">
            {generating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCw className="w-3.5 h-3.5" strokeWidth={1.6} />} Regenerate
          </button>
          <button onClick={() => onPersist(list)} disabled={saving || empty} className="flex-1 py-2.5 rounded-xl bg-[#B48B40] text-black text-sm font-semibold hover:bg-[#c99840] disabled:opacity-50 inline-flex items-center justify-center gap-2">
            {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Check className="w-3.5 h-3.5" strokeWidth={2.5} />} Save list
          </button>
        </div>
      </div>
    </div>
  );
}
