import type { Metadata } from "next";
import { LegalShell, Section, P, Bullet } from "@/components/legal/LegalShell";

export const metadata: Metadata = {
  title: "Disclaimer — Flowstate AI",
  description: "Health, fitness, AI, and use-at-your-own-risk disclaimer for Flowstate AI.",
};

const EFFECTIVE_DATE = "June 10, 2026";

export default function DisclaimerPage() {
  return (
    <LegalShell
      title="Disclaimer"
      effective={EFFECTIVE_DATE}
      intro="The short version: Flowstate gives you training and nutrition guidance generated by AI and surfaced by an app. It is not medical care. Use judgment. If anything hurts or feels wrong, stop and see someone qualified."
    >
      <Section title="Not medical advice">
        <P>
          Flowstate is not a doctor, registered dietitian, physical therapist, or therapist. The content of the app — programs,
          plans, AI replies, coaching cues, form-check feedback, meal suggestions, hydration targets — is general fitness and
          nutrition information. It is not a substitute for professional medical, mental-health, or nutritional advice,
          diagnosis, or treatment.
        </P>
        <P>
          Always seek the advice of a qualified healthcare provider with any questions you may have regarding a medical
          condition, medication, supplement, injury, or program. Never disregard professional advice or delay in seeking
          it because of something you read or saw in Flowstate.
        </P>
      </Section>

      <Section title="Talk to your doctor before starting">
        <P>
          Especially if any of these are true: you have a heart condition, high or low blood pressure, asthma, diabetes,
          osteoporosis, or any chronic condition; you&apos;re pregnant, postpartum, or trying to conceive; you&apos;re
          recovering from injury, surgery, or illness; you take medication (including thyroid medication, blood pressure
          medication, mental-health medication, or weight-loss medication); you have a history of disordered eating;
          you&apos;re under 18.
        </P>
      </Section>

      <Section title="Listen to your body">
        <ul className="space-y-2 pl-0 list-none">
          <Bullet>Stop immediately if you feel chest pain, severe shortness of breath, dizziness, light-headedness, or sharp joint pain.</Bullet>
          <Bullet>Stop and seek care for: pain that doesn&apos;t resolve, swelling, numbness, persistent fatigue, unexplained weight loss or gain, mood changes.</Bullet>
          <Bullet>Warm up. Hydrate. Eat enough. Sleep.</Bullet>
        </ul>
      </Section>

      <Section title="AI-generated content">
        <P>
          The coach chat, the form-check reads, the meal parser, the nutrition planner, and certain images are produced by
          AI models. AI is not deterministic. It can be confidently wrong, omit important context, or misread the
          situation in front of it. Treat AI output as a thoughtful starting point, not a final verdict. The more
          specific the question, the better the answer — and the more important your own judgment becomes.
        </P>
        <P>
          We try to keep the AI honest with strong system instructions, conservative defaults, and refusal to give
          medical advice. None of that is a guarantee.
        </P>
      </Section>

      <Section title="Form check feature">
        <P>
          The AI form check reads a stack of frames from a video you upload. It does not see depth, joint angles in 3D,
          or your individual biomechanics. Its feedback is a coach&apos;s first impression — not a diagnosis. If the AI
          flags a movement, take that as a hint to slow down and verify; if it greenlights a movement, that doesn&apos;t
          mean it&apos;s safe for you specifically.
        </P>
      </Section>

      <Section title="Nutrition guidance">
        <P>
          Calorie targets, macro splits, meal plans, and food images in Flowstate are generated from formulas (BMR / TDEE),
          your stated goal, and AI. They are starting points for healthy adults without medical conditions. They are not a
          treatment plan, a clinical diet, or an eating-disorder recovery plan. If you have or have had an eating disorder,
          do not use Flowstate&apos;s tracking features without working with a clinician.
        </P>
      </Section>

      <Section title="Use at your own risk">
        <P>
          You are responsible for how you use the app. By using Flowstate, you accept the risks inherent in strength
          training, conditioning, and nutritional change. You release Flowstate, its operators, and its trainers from
          liability for injury, illness, or loss arising from following any program, plan, or AI suggestion within the app,
          to the maximum extent allowed by law. This does not limit liability that cannot be limited by law (gross
          negligence, willful misconduct, fraud).
        </P>
      </Section>

      <Section title="Trainers on the platform">
        <P>
          When a trainer is involved, that relationship is between you and the trainer. Flowstate provides the tools and
          the app surface; we do not credentialize, supervise, or guarantee the advice of trainers operating on the
          platform.
        </P>
      </Section>

      <Section title="Questions">
        <P>
          If anything in here is unclear, email{" "}
          <a href="mailto:xavellis4@gmail.com" className="text-[#B48B40] hover:underline">xavellis4@gmail.com</a>.
        </P>
      </Section>
    </LegalShell>
  );
}
